### ISSUE TITLE
Drawbridges don't function in certain chunks.

### ISSUE THREAD

**Issue by Noavailablenames** [SlimeKnights/TinkersMechworks#104] opened 2020-06-18 21:47 UTC
I tested chunk borders to see if it made a difference and in some chunks drawbridges are unable to activate. They work fine in the nether and other areas but in the chunks mostly surrounding my base don't seem to be able to activate them. Another area of the map has the same issue and it's seems to be a pretty large area.

**Comment by KnightMiner** [comment] 2020-06-18 23:24
Do you notice any pattern in those chunks? For example, what are the coordinates of some samples that work or do not work?

**Comment by Noavailablenames** [comment] 2020-06-19 02:49
x960.788 / Y135.42568 / -10.775 is a totally unmodified chunk. I am running other mods but it seems to very much be situated around my area. And a friend said it was the same for him in specific chunks. This is on an mp server.

**Comment by fuj1n** [comment] 2020-06-19 04:15
Unable to reproduce, could you please attach a server log after triggering the issue.

Also, make sure you're not standing in front of the drawbridge whilst activating it, as currently entities block the drawbridge.

**Comment by TherminatorX** [comment] 2020-06-19 16:55
Also could be an issue with the fake player and/or world protection.

**Comment by Noavailablenames** [comment] 2020-06-19 18:25
> Also could be an issue with the fake player and/or world protection.

I tested it on the border of claimed chunks. I'm using FTB chunks for land protection claiming and it appears that when in the wilderness there is no issue with it but when it's inside my land claim there is :D Any way to fix this? I feel like I've had this issue in the past and there was a solution. I appreciate the help :)

**Comment by Noavailablenames** [comment] 2020-06-19 18:33
![image](https://user-images.githubusercontent.com/66493178/85169431-a549db80-b220-11ea-8c9d-af5d87d9e76d.png)
**** FTBC Claim menu.

**Comment by fuj1n** [comment] 2020-06-19 20:07
Oh, it's definitely chunk protection.

What version of Mechworks are you using? As of 2.1.1 there should only be a single Mechworks Worker, before that, every drawbridge had their own and they had inconsistent ids, so if you're using an older version, you have to give them all access, and redo it every server restart. 

#100

**Comment by Noavailablenames** [comment] 2020-06-21 07:20
2.1.0

**Comment by fuj1n** [comment] 2020-06-21 11:26
In that case, the solution is to update to 2.1.1, that way, you only need to whitelist the one Mechworks Worker for your protected chunks.

I'll close this, if this is still an issue in 2.1.1 and beyond, please reply to this.

**Closed by fuj1n** 2020-06-21 11:26 UTC
Labels: under-investigation
