### ISSUE TITLE
Signal Bus and WAILA

### ISSUE THREAD

**Issue by Maleia** [SlimeKnights/TinkersMechworks#82] opened 2015-03-23 18:00 UTC
Signal buses placed in the world when looking at them with WAILA installed crashes the client.

http://pastebin.com/4UDyT2nx

Latest versions of both mods; server/client set up.

**Comment by TherminatorX** [comment] 2015-03-23 20:56
Are we sure it's not on @ProfMobius 's side?

**Comment by Maleia** [comment] 2015-03-24 05:23
Considering all of the issues with Signal Bus and Drawbridges in the past, I figured it would be helpful to notify.  I posted to both of ya'lls' threads.

**Comment by TherminatorX** [comment] 2015-03-24 14:50
Does this happen when the pop-up is hidden?

**Comment by Maleia** [comment] 2015-03-24 15:00
Yes it does.

**Comment by ProfMobius** [comment] 2015-03-24 15:20
The overall location of the crash on my side makes very little sense.
```java
56		this.dim  = ent.getWorldObj().provider.dimensionId;
57		this.posX = ent.xCoord;
```
Looks like the client is passing a broken TE to the request packet. From what I see, the TE has a null posX value, which shouldn't be possible.

**Comment by TherminatorX** [comment] 2015-03-24 17:47
What earliest version of TMech does this work with?
The last commit I can see that would really make a difference would be https://github.com/SlimeKnights/TinkersMechworks/commit/6b209c47caa83d37708b912d6fc81e659122070e

**Comment by Maleia** [comment] 2015-03-24 17:57
It has never worked for us in 1.7.10 (We were previously using 1.6.4) so I don't have a clear answer; we initially tried TMech 0.2.13.96; but it was also suffering from the same issue, and why we attempted updating.

**Comment by ProfMobius** [comment] 2015-03-24 18:04
I was totally unaware of this problem. I'm going to run some tests on my side to see what is going on.
The really weird part is that it is happening at a location where everything is supposed to be set on the TE side, on a field that isn't supposed to be null.

**Comment by ProfMobius** [comment] 2015-03-25 16:10
I can't reproduce the problem. By the look of it, it might be an xmod problem without another mod doing something to the TE while Waila is processing it.
Any chance you can provide a list of mods and what version of Forge or Cauldron you are running ?

**Comment by Maleia** [comment] 2015-03-25 16:27
Hmm, here is the entire list of mods (yea, we have a lot).

Forge 1307

OmniOcular
ForgeMicroblock@1.1.1.325,
guilib@1.0.7.2,
ExtraBees@2.0-pre7,
DynamicLights@1.3.7,
armourersWorkshop@1.7.10-0.28.0.72,
HardcoreEnderExpansion@1.7.1,
MagicBees@1.7.10-2.1.22,
Botany@2.0-pre7,
ProjRed|Integration@4.5.8.59,
Mystcraft@0.11.0.00,
bspkrsCore@6.16,
exastris@MC1.7.10-1.16-21,
DragonMounts@r41-1.7.10,
MagicYarn@1.1.5,
McMultipart@1.1.1.325,
BiomesOPlenty@2.1.0,
ExtraUtilities@1.2.2,
Artifacts@1.1.1,
Railcraft@9.5.0.0,
ForgeMultipart@1.1.1.325,
headcrumbs@1.3.1,
AS_MultiMine@1.4.3,
CoFHCore@1.7.10R3.0.0RC5,
MapWriter@2.1.2,
ThaumicHorizons@1.0,
FastCraft@1.19,Forge@10.13.2.1307,
ChickenShed@1.1.3,
ExtraTrees@2.0-pre7,
MSC2@1.2.1,
ImmibisCore@59.0.8,
ThaumicTinkerer@unspecified,
ExtraTiC@0.8.4,
DynamicLights_creepers@1.0.4,
flowercraftmod@1.9,
slabcraftmod@1.7,
cuchaz.ships@1.7.10-1.0.2,
IguanaTweaksTConstruct@1.7.10-2.1.4.132,
FML@7.10.88.1307,
NEIAddons|Forestry@1.12.4.16,
TiCTooltips@1.2.3,
magicalcrops@1.7.2 - 0.1 ALPHA,
bigtrees@1.7.2b,
NotEnoughCodecs@0.3,
<CoFH ASM>@000,
NEIAddons|CraftingTables@1.12.4.16,
NEIAddons|ExNihilo@1.12.4.16,
AS_UpdateCheck@1.1.6,
WailaHarvestability@1.1.2,
ProjRed|Illumination@4.5.8.59,
TMechworks@0.2.14.100,
Artifice@1.7.10R1.1.4,
Botania@r1.5-169,
yegamolchattels@1.1.1.1,
NotEnoughItems@1.0.4.90,
Thaumcraft@4.2.3.5,
exnihilo@1.37,
Waila@1.5.10,
ProjRed|Compatibility@4.5.8.59,
TConstruct@1.7.10-1.8.3.build919,
ProjectZulu|Core@1.7.10-1.4b4,
ServerTools-PERMISSION@1.7.10-2.2.1.7,
NEIAddons@1.12.4.16,
BinnieCore@2.0-pre7,
haycraftmod@1.7,
BiblioCraft@1.9.2,
MooFluids@1.7.10-1.5.01.19a,
OpenModsCore@0.6,
STPPlugin@,
ivtoolkit@IvToolkit,
MetallurgyCore@4.0.4,
Genetics@2.0-pre7,
mcp@9.05,
Mantle@1.7.10-0.3.2.jenkins184,
ProjRed|Transmission@4.5.8.59,
staircraftmod@1.7,
inventorytweaks@1.58-147-645ca10,
ServerTools-BACKUP@1.7.10-2.2.0.23,
is_mtc@1.7.7,
UtilityMobs@3.1.1,
fossil@1.7.10 Build 7.0.1,
TwilightForest@2.3.4,
ServerTools@1.7.10-2.2.0.79,
OpenBlocks@1.3,
EnderStorage@1.4.5.27,
MineFactoryReloaded@1.7.10R2.8.0RC7,
DimensionalAnchors@59.0.2,
eplus@3.0.2-d,
Aquaculture@1.2.3,
BattleTowers@1.5.1,
OmniOcularCore@1.0,
neiintegration@1.0.7,
ServerTools-TELEPORT@1.0,
Enchiridion@1.1,
MrTJPCoreMod@1.0,
IronChest@6.0.62.742,
NBTEdit@1.7.2.2,
NEIAddons|Botany@1.12.4.16,
tickDynamic@0.1.5,
CodeChickenCore@1.0.4.29,
Treecapitator@1.7.10,
ThaumicTinkerer-preloader@0.1,
DamageIndicatorsMod@3.2.3,
cuchaz.ships.core@1.7.10-1.0.2,
chocolateQuest@1.0,
adventurebackpack@1.7.10-0.8b,
zcraftingmanager@1.1.0,
chisel@2.3.7.34,
Baubles@1.0.1.10,
BetterTitleScreen@1.7.10-1.1,
ProjRed|Core@4.5.8.59,
Backpack@2.0.1,
AS_Ruins@14.7,
Forestry@3.4.0.7,
OpenMods@0.6,
Metallurgy@4.0.8,

I removed a few recurring compatibility mods (MFR/Dynamic Lights) from the list since it only inflated them.

**Comment by ProfMobius** [comment] 2015-03-25 16:37
Any chance you can start with only Waila + Mechwork and add back mods slowly until you find the 3rd mod breaking things up ?
I was not able to reproduce the prb with only Waila and Mechwork, so another mod must be triggering the prb.

**Comment by Maleia** [comment] 2015-03-25 16:47
Yes, it might take some time here but I'll start now.

**Comment by Maleia** [comment] 2015-03-25 17:11
Okay, I have some information, I was able to strip down to the barest of mods and replicate the issue.  Having:

Mantle 0.3.2
NBTEdit
OmniOcular 1.0build28
TConstruct 1.83b
TMechworks 0.2.14.100
WAILA 1.5.10
CodeChickenCore 1.0.4.29
NEI 1.0.4.90


I am able to replicate the issue.  

It happened once I installed OmniOcular, I would like to point out that we were having the issue before when using WAILANBT as well.  But since we updated the entire set of WAILA/Harvestablity, and TMechworks, it wasn't clear.

If I need to send this information off to another party, let me know; happily do so and reference this ticket :)

**Comment by ProfMobius** [comment] 2015-03-25 17:23
Whoot, didn't even know someone remade WailaNBT (it was mostly a small debugging tool I made) and made it way better. That's cool.
Can you tell me something ? Do you have any rules for Signal Buses in your OmniOcular config ? And if so, can you remove the rule and try again ?
Also, can you try to add a rule for another block with TileEntity and see if it crashes ?

With those new results, I suspect now that they are making a copy of the TileEntity to display in the tooltip, but this TE is never registered properly with the world (hence the crash you are observing).

**Comment by Maleia** [comment] 2015-03-25 17:55
I haven't done anything special to OmniOcular, so it's running on default settings.  (We've only been using it for a few days now, and haven't had time to fully investigate what we can do with it other than editing NBT items).

I don't have the capacity to make changes to the OO's config really and will have to get with one of my other team members, which will take some time.  In the mean time though, I'll send this ticket over to Omni.  Unless you think there's anything else Prof, then I think this is concluded here and we'll remove OmniOcular for the time being.

**Comment by ProfMobius** [comment] 2015-03-25 19:27
Can't really think of anything else.
I will check OmniOcular code when I have time. Really interrested in the whole XML described module system :)
Maybe I will be able to pinpoint more precisly where the prb occurs.

Cheers.

I think this issue should be closed since it is neither a direct Waila or Mechworks problem.

**Comment by Glassmaker** [comment] 2015-03-25 21:03
Okeo, Closing the issue. :)

**Comment by exzhawk** [comment] 2015-04-23 14:09
SignalBusLogic class override the getWorldObj() method. OmniOcular requests Waila sync all TileEntity. When SignalBusLogic is being synced, Waila call getWorldObj and get a null.
I rarely see one override getWorldObj method... is it so necessary in SignalBusLogic?

**Comment by exzhawk** [comment] 2015-07-20 02:53
Fixed in OmniOcular build58. I exclude SignalBus when registering waila hooks.

**Comment by RisingDemon** [comment] 2015-08-30 22:13
I don't have OmniOcular, but I get the same crash. Just updated to the latest WAILA/TMech builds (TMechworks-1.7.10-0.2.14.100.jar and Waila-1.5.10_1.7.10.jar) and it didn't change. I love both mods, but after the 1.7 update to TMech, I've only been able to use basic drawbridges - I tried using an advanced one and crashed, ClassCastException when some code was running on the wrong side in TMech. I've lost count of how many times I've had to load my world in mcedit and remove a block from TMech just so I could go back in.

**Comment by Glassmaker** [comment] 2015-12-22 08:35
Reopening for re-investigation.

**Comment by exzhawk** [comment] 2015-12-22 09:20
Like what i said, SignalBusLogic override getWorldObj() and can return null. Then WAILA throw NPE when trying to sync it. Still cant get necessary of overriding it. I guess Pneumatic Craft also registered all blocks/TEs including Signal Bus.

**Comment by Glassmaker** [comment] 2015-12-23 18:34
Thanks @exzhawk for the heads up, 
going back into the comments history I found this https://github.com/SlimeKnights/TinkersMechworks/commit/66db052a8e088360dbca3a04f3309dc466353998#diff-ac35dad23b06a113f9b89b9b9804fb96, so it was added for some fix.

The comment includes multiple fixes and message is vague regarding the type of fixes were done, will see if removing the override would cause issues.

**Closed** 2015-12-23 19:48 UTC
Labels: under-investigation
