### ISSUE TITLE
Request ability for camouflage of the drawbridge to be rotated

### ISSUE THREAD

**Issue by ClaudiusMinimus** [SlimeKnights/TinkersMechworks#103] opened 2020-06-08 15:02 UTC
I'm using Tinkers' Mechworks 1.15.2-2.1.1 in my pack in development with a lot of other mods, including Macaw's Bridges (https://www.curseforge.com/minecraft/mc-mods/macaws-bridges). The issue at hand is shown in the attached image. If the Drawbridge is pointed East to West, then the Macaw's Bridge section used as camouflage displays correctly. However, if the Drawbridge is pointed North to South, the Macaw's Bridge section still points East to West. Is there a way to rotate the block used as the camouflaged item?
![correctBridge](https://user-images.githubusercontent.com/17887664/84045739-67b69a00-a966-11ea-9912-145174e6773e.png)

**Comment by KnightMiner** [comment] 2020-06-08 16:21
One suggestion is to set the fake player facing based on the drawbridge direction before placing blocks, as most block orientations are based on player facing.

**Comment by fuj1n** [comment] 2020-06-19 04:25
Could you please attach a screenshot of the block state information (right side of the F3 screen) of an actual bridge block? Currently, the rotation should be copied correctly assuming that the block in question actually uses vanilla's "facing" state.

**Comment by KnightMiner** [comment] 2020-06-19 04:34
If I had to guess, they use an axis state instead of facing, as north and south are redundant, and east and west are redundant.

**Comment by fuj1n** [comment] 2020-06-19 05:47
Potentially fixed by https://github.com/SlimeKnights/TinkersMechworks/commit/e987a7c3aca9f3f8d0df36a08595a2114eea05a7

**Comment by fuj1n** [comment] 2020-06-19 06:08
Please test with version 2.2.0

CurseForge: https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks/files/2983555

**Comment by ClaudiusMinimus** [comment] 2020-06-19 22:47
I just tried version 2.2.0 and it is the same issue. I hope the screenshot helps. 

![2020-06-19_16 45 10](https://user-images.githubusercontent.com/17887664/85184275-62056200-b24c-11ea-970e-0ef1c6867fe5.png)

**Comment by fuj1n** [comment] 2020-06-19 23:20
I just tested it, and it does work, the problem is Macaw's Bridges facing direction is rotated 90 degrees from what you'd expect (i.e, a bridge that is rendered facing south has a state that says it faces west) for some odd reason.

![image](https://user-images.githubusercontent.com/4004193/85185143-1bf4e080-b2d6-11ea-8197-e3ddd41becab.png)

Since 2.2.0, no longer a TMechs issue as the direction is handled correctly.

You can try reporting it to [their issue tracker](https://github.com/sketchmacaw/MacawsModsIssues/issues), but I don't think they'll fix it, as doing so would rotate all existing bridges 90 degrees. If they want to, Mechworks does provide a barebones API to change how the rotation is applied to blocks.

**Closed by fuj1n** 2020-06-19 23:20 UTC
Labels: bug, under-investigation

**Comment by ClaudiusMinimus** [comment] 2020-06-20 01:04
Thanks!
